GET http://localhost:5678/hello
Accept: application/json

###

POST http://localhost:8088/hello-post
Content-Type: application/json

{}

###

POST http://localhost:8088/hello-post-param
Content-Type: application/x-www-form-urlencoded

name=Test

###

GET http://localhost:5678/test-list
Accept: application/json

###